# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: CRM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install coverage.py and pytest
        run: |
            pip install coverage
            pip install pytest
      
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          if: "${{ runner.os }}" == "Windows"
            .\venv\Scripts\activate
          if: "${{ runner.os }}" != "Windows"
            source venv/bin/activate
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Tests with Coverage
        run: |
          coverage run -m unittest discover -s test/unit -p '*_test.py'
          coverage run -m pytest test/integration
          # coverage run -m pytest test/system
        
      - name: Generate coverage report
        run: coverage xml -o coverage.xml
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'MessageMonitorMoonBreezes'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8BE7F63713554E58B3BE7052106D46F6 }}
